modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Configurable%20Furnace%20Burn%20Time"
logoFile="icon.png"

[[mods]]
modId="configurablefurnaceburntime"
version="2.4"
displayName="Configurable Furnace Burn Time"
displayURL="https://serilum.com/mod/configurable-furnace-burn-time"
authors="Rick South"
description='''Allows users to change the fuel burn time in a furnace globally via a config.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., Nahuel Fernandez, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.configurablefurnaceburntime]]
    modId="collective"
    type="required"
    versionRange="[7.78,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.configurablefurnaceburntime]]
    modId="minecraft"
    type="required"
    versionRange="[1.21]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "configurablefurnaceburntime.mixins.json"